#!/usr/bin/env python3
"""Generate the qualitative-comparison table (paper Table 2 material):
for a handful of interesting balls, show the structured input, each system's
generation, and the fact checker's verdict — side by side, script-generated
like every other artifact (§10: no hand-made tables).

Balls are chosen by category (wicket, six, four, dot-under-pressure, tense
chase ball) from the rows shared by ALL selected runs, keyed by
(match_id, innings, over, delivery_seq). Runs are the non-mini, non-smoke
set by default; pass explicit --runs-dirs to override.

Usage:
    python scripts/make_examples.py                       # auto-select runs
    python scripts/make_examples.py --runs-dirs results/runs/A results/runs/B
"""

from __future__ import annotations

import argparse
from pathlib import Path

from cricket_commentary.eval.factcheck import check_generation
from cricket_commentary.eval.report import load_all_runs
from cricket_commentary.utils.io import read_jsonl
from cricket_commentary.utils.seeding import rng_for

CATEGORIES = ["wicket", "six", "four", "dot_death", "tense_chase"]


def _key(record: dict) -> tuple:
    return (record["match_id"], record["innings"], record["over"],
            record.get("delivery_seq", record["ball"]))


def _category(row: dict) -> str | None:
    record, features = row["record"], row["features"]
    if record["wicket"]:
        return "wicket"
    if record["runs_batter"] == 6:
        return "six"
    if record["runs_batter"] == 4:
        return "four"
    if record["runs_total"] == 0 and features["phase"] == "death":
        return "dot_death"
    if record["target"] is not None and features["tension"] > 0.6:
        return "tense_chase"
    return None


def _verdict(text: str, record: dict) -> str:
    res = check_generation(text, record)
    if not res.violations and not res.omissions:
        return "ok"
    parts = [f"{v['slot']}: claimed {v['claimed']}, actual {v['actual']}"
             for v in res.violations]
    parts += res.omissions
    return "; ".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", default="results/runs")
    parser.add_argument("--runs-dirs", nargs="*", help="explicit run dirs to compare")
    parser.add_argument("--out", default="results/tables")
    parser.add_argument("--per-category", type=int, default=1)
    parser.add_argument("--seed", type=int, default=13)
    args = parser.parse_args()

    runs = load_all_runs(args.runs)
    if args.runs_dirs:
        wanted = {str(Path(d)) for d in args.runs_dirs}
        runs = [r for r in runs if r["run_dir"] in wanted]
    else:
        runs = [r for r in runs
                if not r["run"]["name"].endswith("_mini")
                and not r["run"]["name"].startswith("smoke_")]
    # one run per system name (drop seed repeats)
    seen: set[str] = set()
    selected = []
    for run in runs:
        name = run["run"]["name"]
        base = name.rsplit("_seed", 1)[0]
        if base in seen:
            continue
        seen.add(base)
        selected.append(run)
    if not selected:
        raise SystemExit("no runs to compare")

    # rows + generations per run, keyed per delivery
    per_run: dict[str, dict] = {}
    row_lookup: dict[tuple, dict] = {}
    for run in selected:
        meta = run["run"]
        rows = read_jsonl(meta["data"])
        if meta.get("split", "all") != "all":
            rows = [r for r in rows if r["split"] == meta["split"]]
        gens = read_jsonl(Path(run["run_dir"]) / "generations.jsonl")
        mapping = {}
        for row, gen in zip(rows, gens):
            mapping[_key(row["record"])] = gen["generation"]
            row_lookup[_key(row["record"])] = row
        per_run[meta["name"]] = mapping

    shared = set.intersection(*(set(m) for m in per_run.values()))
    if not shared:
        raise SystemExit("selected runs share no deliveries — compare runs "
                         "evaluated on the same data/split")

    rng = rng_for(args.seed, "examples")
    chosen: list[tuple] = []
    for category in CATEGORIES:
        pool = sorted(k for k in shared if _category(row_lookup[k]) == category)
        take = min(args.per_category, len(pool))
        if take:
            chosen += [pool[i] for i in
                       sorted(rng.choice(len(pool), size=take, replace=False).tolist())]

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    names = sorted(per_run)

    md = ["# Qualitative examples",
          "",
          "Script-generated by scripts/make_examples.py — inputs, outputs and "
          "checker verdicts side by side.", ""]
    tex = ["% generated by scripts/make_examples.py — do not edit by hand",
           "\\begin{table*}[t]\\centering\\small",
           "\\begin{tabular}{p{0.32\\textwidth}" + "p{0.3\\textwidth}" * len(names) + "}",
           "\\toprule",
           "Input & " + " & ".join(n.replace("_", "\\_") for n in names) + " \\\\",
           "\\midrule"]

    for key in chosen:
        row = row_lookup[key]
        category = _category(row)
        md.append(f"## {category} — {key[0]} innings {key[1]}, over "
                  f"{key[2] - 1}.{row['record']['ball']}")
        md.append(f"\n`{row['linearized_input']}`\n")
        md.append("| system | generation | checker verdict |")
        md.append("|---|---|---|")
        tex_cells = []
        for name in names:
            text = per_run[name][key]
            verdict = _verdict(text, row["record"])
            md.append(f"| {name} | {text} | {verdict} |")
            marker = "" if verdict == "ok" else " \\textsuperscript{!}"
            tex_cells.append(text.replace("&", "\\&") + marker)
        md.append("")
        input_tex = row["linearized_input"].replace("|", "$\\vert$").replace("_", "\\_")
        tex.append(f"\\texttt{{{input_tex}}} & " + " & ".join(tex_cells) + " \\\\")

    tex += ["\\bottomrule", "\\end{tabular}",
            "\\caption{Qualitative examples. \\textsuperscript{!} marks outputs "
            "the fact checker flagged (details in the generated markdown twin).}",
            "\\label{tab:examples}", "\\end{table*}"]

    (out_dir / "qualitative_examples.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    (out_dir / "qualitative_examples.tex").write_text("\n".join(tex) + "\n", encoding="utf-8")
    print(f"wrote {out_dir}/qualitative_examples.md and .tex "
          f"({len(chosen)} balls x {len(names)} systems)")


if __name__ == "__main__":
    main()
