#!/usr/bin/env python3
"""Aggregate all run directories into results/tables/main_results.{md,tex}.

Runs whose names differ only by a ``_seed<N>`` suffix are one system evaluated
under multiple seeds and are reported as mean ± std (§6 headline protocol).
Metrics that a run recorded as unavailable/blocked render as "—" — never
imputed (§2 rule 7). Fixture-scale golden-path runs (``*_mini``) are excluded
unless --include-mini is passed.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from statistics import mean, stdev

from cricket_commentary.eval.report import load_all_runs

_SEED_TAG = re.compile(r"_seed\d+$")

COLUMNS = [
    ("halluc", "Halluc.$\\downarrow$", "Halluc↓"),
    ("omit", "Omit$\\downarrow$", "Omit↓"),
    ("calib", "Calib $\\rho\\uparrow$", "Calib ρ↑"),
    ("bleu", "BLEU", "BLEU"),
    ("rouge", "ROUGE-L", "ROUGE-L"),
    ("bert", "BERTSc.", "BERTSc"),
    ("dist2", "Dist-2$\\uparrow$", "Dist-2↑"),
    ("selfbleu", "S-BLEU$\\downarrow$", "SelfBLEU↓"),
    ("rep", "Rep$\\downarrow$", "Rep4g↓"),
    ("p50", "p50 ms$\\downarrow$", "p50ms↓"),
]


def _numeric(value):
    return value if isinstance(value, (int, float)) and not isinstance(value, bool) else None


def extract(run: dict) -> dict:
    metrics = run["metrics"]
    faith = metrics.get("faithfulness", {})
    excite = metrics.get("excitement", {})
    surf = metrics.get("surface", {})
    div = metrics.get("diversity", {})
    lat = metrics.get("latency", {})
    rep_key = next((k for k in div if k.startswith("repetition_")), "")
    bert = surf.get("bert_score", {})
    return {
        "name": run["run"].get("name", "?"),
        "system": run["run"].get("system", "?"),
        "n": run["run"].get("n_rows"),
        "halluc": _numeric(faith.get("hallucination_rate")),
        "omit": _numeric(faith.get("omission_rate")),
        "calib": _numeric(excite.get("calibration", {}).get("spearman_rho")),
        "bleu": _numeric(surf.get("bleu")),
        "rouge": _numeric(surf.get("rouge_l")),
        "bert": _numeric(bert.get("f1") if isinstance(bert, dict) else None),
        "dist2": _numeric(div.get("distinct_2")),
        "selfbleu": _numeric(div.get("self_bleu")),
        "rep": _numeric(div.get(rep_key)),
        "p50": _numeric(lat.get("p50_ms") if isinstance(lat, dict) else None),
    }


def group_rows(rows: list[dict]) -> list[dict]:
    groups: dict[str, list[dict]] = {}
    for row in rows:
        key = _SEED_TAG.sub("", row["name"])
        groups.setdefault(key, []).append(row)

    out = []
    for key in sorted(groups):
        members = groups[key]
        agg = {"name": key, "system": members[0]["system"], "n": members[0]["n"],
               "seeds": len(members)}
        for col, _, _ in COLUMNS:
            values = [m[col] for m in members if m[col] is not None]
            # partial=True when only a subset of the group's runs reported the
            # metric — rendered with a marker so it can't pass as a full mean
            partial = 0 < len(values) < len(members)
            if not values:
                agg[col] = None
            elif len(values) == 1:
                agg[col] = (values[0], None, partial)
            else:
                agg[col] = (mean(values), stdev(values), partial)
        out.append(agg)
    return out


def _fmt(cell, digits=3) -> str:
    if cell is None:
        return "—"
    value, spread, partial = cell
    text = f"{value:.{digits}f}"
    if spread is not None:
        text += f" ± {spread:.{digits}f}"
    if partial:
        text += "*"  # metric missing from some runs in the seed group
    return text


def write_tables(grouped: list[dict], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    md = ["| System | n | seeds | " + " | ".join(h for _, _, h in COLUMNS) + " |",
          "|" + "---|" * (3 + len(COLUMNS))]
    for g in grouped:
        cells = " | ".join(_fmt(g[c]) for c, _, _ in COLUMNS)
        md.append(f"| {g['name']} | {g['n']} | {g['seeds']} | {cells} |")
    (out_dir / "main_results.md").write_text(
        "# Main results\n\nAggregated from results/runs by scripts/make_tables.py — "
        "'—' means the metric was recorded unavailable/blocked for that run, "
        "never imputed. 'seeds' counts aggregated runs; a '*' marks a value "
        "reported by only a subset of the group's runs.\n\n" + "\n".join(md) + "\n",
        encoding="utf-8",
    )

    tex = [
        "% generated by scripts/make_tables.py — do not edit by hand",
        "\\begin{table*}[t]\\centering\\small",
        "\\begin{tabular}{l r " + "r " * len(COLUMNS) + "}",
        "\\toprule",
        "System & $n$ & " + " & ".join(h for _, h, _ in COLUMNS) + " \\\\",
        "\\midrule",
    ]
    for g in grouped:
        name = g["name"].replace("_", "\\_")
        cells = " & ".join(_fmt(g[c]) for c, _, _ in COLUMNS)
        tex.append(f"{name} & {g['n']} & {cells} \\\\")
    tex += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Main results. Values are mean $\\pm$ std over seeds where "
        "multiple seeded runs exist; --- marks metrics recorded unavailable in "
        "the run environment.}",
        "\\label{tab:main}",
        "\\end{table*}",
    ]
    (out_dir / "main_results.tex").write_text("\n".join(tex) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", default="results/runs")
    parser.add_argument("--out", default="results/tables")
    parser.add_argument("--include-mini", action="store_true")
    parser.add_argument("--include-smoke", action="store_true",
                        help="include smoke_* machinery-validation runs")
    args = parser.parse_args()

    runs = load_all_runs(args.runs)
    if not runs:
        raise SystemExit(f"no runs with metrics.json under {args.runs}")
    rows = [extract(r) for r in runs]
    if not args.include_mini:
        rows = [r for r in rows if not r["name"].endswith("_mini")]
    if not args.include_smoke:
        # smoke_* runs exercise machinery on random-init models; their
        # numbers are meaningless as results
        rows = [r for r in rows if not r["name"].startswith("smoke_")]
    grouped = group_rows(rows)
    write_tables(grouped, Path(args.out))
    print(f"wrote {args.out}/main_results.md and .tex ({len(grouped)} systems, "
          f"{len(rows)} runs)")


if __name__ == "__main__":
    main()
